services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      #- /app/node_modules
    ports:
    - "3000:3000"
    - "5173:5173"
    #command: ["npm", "run", "dev"]
    command: ["bash"]
    stdin_open: true      # ← garde STDIN ouvert (équiv. à -i)
    tty: true             # ← alloue un terminal (équiv. à -t)
    profiles:
      - dev

  prod:
    build:
      context: .
      target: prod
    volumes:
      - .:/app
      - /app/node_modules
    ports:
    - "3000:3000"
    - "5173:5173"
    command: ["node", "dist/index.js"]
    profiles:
      - prod
