services:
  dev:
    container_name: trans-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: dev
    # ports:
    #   - "3000:3000"
    #   - "5173:5173"
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=true
    image: dev
    restart: unless-stopped

  prod:
    container_name: trans-prod
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: prod
    ports:
    - "3000:3000"
    environment:
      - NODE_ENV=production
    image: prod
